
name: Lint
  
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.19
        uses: actions/setup-go@v5
        with:          
          go-version: 1.19

      - name: Checkout
        uses: actions/checkout@v4

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.50.0
          go install github.com/mattn/goveralls@latest

      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --out-format=github-actions