on: [push, pull_request]
  
name: Run Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Run tests with coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    - name: Coveralls
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{ secrets.github_token }}
        file: coverage.out
        format: golang