name: Run Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Vet
        run: go vet ./...
      - name: Run tests with coverage
        run: go test -race -v -covermode=atomic -coverprofile=coverage.out ./...
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.out
          format: golang
