
name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.18.x", "1.19.x"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: go test -v -covermode=count
  
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Calc coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.9
    - name: Coveralls
      uses: coverallsapp/github-action@v1.2.4
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
